name: brew pr-pull
on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: 'Pull Request number to publish'
        required: true
jobs:
  pr-pull:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          PULL_REQUEST: ${{ inputs.pull_request }}
        run: brew pr-pull --debug --tap=$GITHUB_REPOSITORY $PULL_REQUEST

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main

      - name: Delete branch
        env:
          PULL_REQUEST: ${{ inputs.pull_request }}
          GH_TOKEN: ${{ github.token }}
        run: |
          branch=`gh pr view $PULL_REQUEST --json headRefName -q .headRefName`
          git push --delete origin $branch
